/** \file
  \brief Arduino-style pin names for STM32F401 / STM32F411.

  Generated table, do not edit by hand. Every pin name, e.g. PA_5, is a bare
  token which is never defined itself. Properties are looked up by token
  pasting through the PIN_xxx() helpers below, so all pin operations resolve
  at compile time into a single register access:

    PIN_PORT(PA_5)     -> GPIOA                  (GPIO_TypeDef *)
    PIN_NUM(PA_5)      -> 5                      (bit number in the port)
    PIN_ID(PA_5)       -> 0x05                   (port index << 4 | bit)
    PIN_ADC(PA_5)      -> 5                      (ADC1 channel or ADC_NONE)
    PIN_TIMER(PA_5)    -> TIM2_BASE              (PWM timer base or 0)
    PIN_CHANNEL(PA_5)  -> 1                      (timer channel 1..4 or 0)
    PIN_AF(PA_5)       -> 1                      (alternate function number)
    PIN_COMPL(PA_5)    -> 0                      (1 = complementary CHxN output)

  Both naming styles known from the Arduino STM32 core are accepted:
  PA_5 (PinName style) and PA5 (pin alias style). Pins not present in a given
  package (e.g. PB11 or PC0 on the 48-pin Blackpill) simply must not be used.

  TIM5 is reserved for the step timer and therefore never listed as PWM timer.
*/

#ifndef _PINS_STM32F4_H
#define _PINS_STM32F4_H

/// Marker for pins without ADC channel.
#define ADC_NONE          0xFF
/// Marker for pins without PWM timer.
#define TIMER_NONE        0

/* Two-level concatenation so that aliases like PA5 get expanded first. */
#define PIN_CAT_(a, b)    a ## b
#define PIN_CAT(a, b)     PIN_CAT_(a, b)

#define PIN_PORT(p)       PIN_CAT(p, _PORT)
#define PIN_NUM(p)        PIN_CAT(p, _PIN)
#define PIN_ID(p)         PIN_CAT(p, _ID)
#define PIN_ADC(p)        PIN_CAT(p, _ADC)
#define PIN_TIMER(p)      PIN_CAT(p, _TIMER)
#define PIN_CHANNEL(p)    PIN_CAT(p, _CHANNEL)
#define PIN_AF(p)         PIN_CAT(p, _AF)
#define PIN_COMPL(p)      PIN_CAT(p, _COMPL)

/// Runtime helpers working on a PIN_ID() value.
#define PIN_ID_PORT(id)   ((GPIO_TypeDef *)(GPIOA_BASE + (((id) >> 4) & 0x0FU) * 0x400UL))
#define PIN_ID_NUM(id)    ((id) & 0x0FU)

/* ---- Port A ---- */
#define PA_0_PORT    GPIOA
#define PA_0_PIN     0
#define PA_0_ID      0x00
#define PA_0_ADC     0
#define PA_0_TIMER   TIM2_BASE
#define PA_0_CHANNEL 1
#define PA_0_AF      1
#define PA_0_COMPL   0
#define PA0          PA_0
#define PA_1_PORT    GPIOA
#define PA_1_PIN     1
#define PA_1_ID      0x01
#define PA_1_ADC     1
#define PA_1_TIMER   TIM2_BASE
#define PA_1_CHANNEL 2
#define PA_1_AF      1
#define PA_1_COMPL   0
#define PA1          PA_1
#define PA_2_PORT    GPIOA
#define PA_2_PIN     2
#define PA_2_ID      0x02
#define PA_2_ADC     2
#define PA_2_TIMER   TIM2_BASE
#define PA_2_CHANNEL 3
#define PA_2_AF      1
#define PA_2_COMPL   0
#define PA2          PA_2
#define PA_3_PORT    GPIOA
#define PA_3_PIN     3
#define PA_3_ID      0x03
#define PA_3_ADC     3
#define PA_3_TIMER   TIM2_BASE
#define PA_3_CHANNEL 4
#define PA_3_AF      1
#define PA_3_COMPL   0
#define PA3          PA_3
#define PA_4_PORT    GPIOA
#define PA_4_PIN     4
#define PA_4_ID      0x04
#define PA_4_ADC     4
#define PA_4_TIMER   TIMER_NONE
#define PA_4_CHANNEL 0
#define PA_4_AF      0
#define PA_4_COMPL   0
#define PA4          PA_4
#define PA_5_PORT    GPIOA
#define PA_5_PIN     5
#define PA_5_ID      0x05
#define PA_5_ADC     5
#define PA_5_TIMER   TIM2_BASE
#define PA_5_CHANNEL 1
#define PA_5_AF      1
#define PA_5_COMPL   0
#define PA5          PA_5
#define PA_6_PORT    GPIOA
#define PA_6_PIN     6
#define PA_6_ID      0x06
#define PA_6_ADC     6
#define PA_6_TIMER   TIM3_BASE
#define PA_6_CHANNEL 1
#define PA_6_AF      2
#define PA_6_COMPL   0
#define PA6          PA_6
#define PA_7_PORT    GPIOA
#define PA_7_PIN     7
#define PA_7_ID      0x07
#define PA_7_ADC     7
#define PA_7_TIMER   TIM3_BASE
#define PA_7_CHANNEL 2
#define PA_7_AF      2
#define PA_7_COMPL   0
#define PA7          PA_7
#define PA_8_PORT    GPIOA
#define PA_8_PIN     8
#define PA_8_ID      0x08
#define PA_8_ADC     ADC_NONE
#define PA_8_TIMER   TIM1_BASE
#define PA_8_CHANNEL 1
#define PA_8_AF      1
#define PA_8_COMPL   0
#define PA8          PA_8
#define PA_9_PORT    GPIOA
#define PA_9_PIN     9
#define PA_9_ID      0x09
#define PA_9_ADC     ADC_NONE
#define PA_9_TIMER   TIM1_BASE
#define PA_9_CHANNEL 2
#define PA_9_AF      1
#define PA_9_COMPL   0
#define PA9          PA_9
#define PA_10_PORT   GPIOA
#define PA_10_PIN    10
#define PA_10_ID     0x0A
#define PA_10_ADC    ADC_NONE
#define PA_10_TIMER  TIM1_BASE
#define PA_10_CHANNEL 3
#define PA_10_AF     1
#define PA_10_COMPL  0
#define PA10         PA_10
#define PA_11_PORT   GPIOA
#define PA_11_PIN    11
#define PA_11_ID     0x0B
#define PA_11_ADC    ADC_NONE
#define PA_11_TIMER  TIM1_BASE
#define PA_11_CHANNEL 4
#define PA_11_AF     1
#define PA_11_COMPL  0
#define PA11         PA_11
#define PA_12_PORT   GPIOA
#define PA_12_PIN    12
#define PA_12_ID     0x0C
#define PA_12_ADC    ADC_NONE
#define PA_12_TIMER  TIMER_NONE
#define PA_12_CHANNEL 0
#define PA_12_AF     0
#define PA_12_COMPL  0
#define PA12         PA_12
#define PA_13_PORT   GPIOA
#define PA_13_PIN    13
#define PA_13_ID     0x0D
#define PA_13_ADC    ADC_NONE
#define PA_13_TIMER  TIMER_NONE
#define PA_13_CHANNEL 0
#define PA_13_AF     0
#define PA_13_COMPL  0
#define PA13         PA_13
#define PA_14_PORT   GPIOA
#define PA_14_PIN    14
#define PA_14_ID     0x0E
#define PA_14_ADC    ADC_NONE
#define PA_14_TIMER  TIMER_NONE
#define PA_14_CHANNEL 0
#define PA_14_AF     0
#define PA_14_COMPL  0
#define PA14         PA_14
#define PA_15_PORT   GPIOA
#define PA_15_PIN    15
#define PA_15_ID     0x0F
#define PA_15_ADC    ADC_NONE
#define PA_15_TIMER  TIM2_BASE
#define PA_15_CHANNEL 1
#define PA_15_AF     1
#define PA_15_COMPL  0
#define PA15         PA_15

/* ---- Port B ---- */
#define PB_0_PORT    GPIOB
#define PB_0_PIN     0
#define PB_0_ID      0x10
#define PB_0_ADC     8
#define PB_0_TIMER   TIM3_BASE
#define PB_0_CHANNEL 3
#define PB_0_AF      2
#define PB_0_COMPL   0
#define PB0          PB_0
#define PB_1_PORT    GPIOB
#define PB_1_PIN     1
#define PB_1_ID      0x11
#define PB_1_ADC     9
#define PB_1_TIMER   TIM3_BASE
#define PB_1_CHANNEL 4
#define PB_1_AF      2
#define PB_1_COMPL   0
#define PB1          PB_1
#define PB_2_PORT    GPIOB
#define PB_2_PIN     2
#define PB_2_ID      0x12
#define PB_2_ADC     ADC_NONE
#define PB_2_TIMER   TIMER_NONE
#define PB_2_CHANNEL 0
#define PB_2_AF      0
#define PB_2_COMPL   0
#define PB2          PB_2
#define PB_3_PORT    GPIOB
#define PB_3_PIN     3
#define PB_3_ID      0x13
#define PB_3_ADC     ADC_NONE
#define PB_3_TIMER   TIM2_BASE
#define PB_3_CHANNEL 2
#define PB_3_AF      1
#define PB_3_COMPL   0
#define PB3          PB_3
#define PB_4_PORT    GPIOB
#define PB_4_PIN     4
#define PB_4_ID      0x14
#define PB_4_ADC     ADC_NONE
#define PB_4_TIMER   TIM3_BASE
#define PB_4_CHANNEL 1
#define PB_4_AF      2
#define PB_4_COMPL   0
#define PB4          PB_4
#define PB_5_PORT    GPIOB
#define PB_5_PIN     5
#define PB_5_ID      0x15
#define PB_5_ADC     ADC_NONE
#define PB_5_TIMER   TIM3_BASE
#define PB_5_CHANNEL 2
#define PB_5_AF      2
#define PB_5_COMPL   0
#define PB5          PB_5
#define PB_6_PORT    GPIOB
#define PB_6_PIN     6
#define PB_6_ID      0x16
#define PB_6_ADC     ADC_NONE
#define PB_6_TIMER   TIM4_BASE
#define PB_6_CHANNEL 1
#define PB_6_AF      2
#define PB_6_COMPL   0
#define PB6          PB_6
#define PB_7_PORT    GPIOB
#define PB_7_PIN     7
#define PB_7_ID      0x17
#define PB_7_ADC     ADC_NONE
#define PB_7_TIMER   TIM4_BASE
#define PB_7_CHANNEL 2
#define PB_7_AF      2
#define PB_7_COMPL   0
#define PB7          PB_7
#define PB_8_PORT    GPIOB
#define PB_8_PIN     8
#define PB_8_ID      0x18
#define PB_8_ADC     ADC_NONE
#define PB_8_TIMER   TIM4_BASE
#define PB_8_CHANNEL 3
#define PB_8_AF      2
#define PB_8_COMPL   0
#define PB8          PB_8
#define PB_9_PORT    GPIOB
#define PB_9_PIN     9
#define PB_9_ID      0x19
#define PB_9_ADC     ADC_NONE
#define PB_9_TIMER   TIM4_BASE
#define PB_9_CHANNEL 4
#define PB_9_AF      2
#define PB_9_COMPL   0
#define PB9          PB_9
#define PB_10_PORT   GPIOB
#define PB_10_PIN    10
#define PB_10_ID     0x1A
#define PB_10_ADC    ADC_NONE
#define PB_10_TIMER  TIM2_BASE
#define PB_10_CHANNEL 3
#define PB_10_AF     1
#define PB_10_COMPL  0
#define PB10         PB_10
#define PB_11_PORT   GPIOB
#define PB_11_PIN    11
#define PB_11_ID     0x1B
#define PB_11_ADC    ADC_NONE
#define PB_11_TIMER  TIM2_BASE
#define PB_11_CHANNEL 4
#define PB_11_AF     1
#define PB_11_COMPL  0
#define PB11         PB_11
#define PB_12_PORT   GPIOB
#define PB_12_PIN    12
#define PB_12_ID     0x1C
#define PB_12_ADC    ADC_NONE
#define PB_12_TIMER  TIMER_NONE
#define PB_12_CHANNEL 0
#define PB_12_AF     0
#define PB_12_COMPL  0
#define PB12         PB_12
#define PB_13_PORT   GPIOB
#define PB_13_PIN    13
#define PB_13_ID     0x1D
#define PB_13_ADC    ADC_NONE
#define PB_13_TIMER  TIM1_BASE
#define PB_13_CHANNEL 1
#define PB_13_AF     1
#define PB_13_COMPL  1
#define PB13         PB_13
#define PB_14_PORT   GPIOB
#define PB_14_PIN    14
#define PB_14_ID     0x1E
#define PB_14_ADC    ADC_NONE
#define PB_14_TIMER  TIM1_BASE
#define PB_14_CHANNEL 2
#define PB_14_AF     1
#define PB_14_COMPL  1
#define PB14         PB_14
#define PB_15_PORT   GPIOB
#define PB_15_PIN    15
#define PB_15_ID     0x1F
#define PB_15_ADC    ADC_NONE
#define PB_15_TIMER  TIM1_BASE
#define PB_15_CHANNEL 3
#define PB_15_AF     1
#define PB_15_COMPL  1
#define PB15         PB_15

/* ---- Port C ---- */
#define PC_0_PORT    GPIOC
#define PC_0_PIN     0
#define PC_0_ID      0x20
#define PC_0_ADC     10
#define PC_0_TIMER   TIMER_NONE
#define PC_0_CHANNEL 0
#define PC_0_AF      0
#define PC_0_COMPL   0
#define PC0          PC_0
#define PC_1_PORT    GPIOC
#define PC_1_PIN     1
#define PC_1_ID      0x21
#define PC_1_ADC     11
#define PC_1_TIMER   TIMER_NONE
#define PC_1_CHANNEL 0
#define PC_1_AF      0
#define PC_1_COMPL   0
#define PC1          PC_1
#define PC_2_PORT    GPIOC
#define PC_2_PIN     2
#define PC_2_ID      0x22
#define PC_2_ADC     12
#define PC_2_TIMER   TIMER_NONE
#define PC_2_CHANNEL 0
#define PC_2_AF      0
#define PC_2_COMPL   0
#define PC2          PC_2
#define PC_3_PORT    GPIOC
#define PC_3_PIN     3
#define PC_3_ID      0x23
#define PC_3_ADC     13
#define PC_3_TIMER   TIMER_NONE
#define PC_3_CHANNEL 0
#define PC_3_AF      0
#define PC_3_COMPL   0
#define PC3          PC_3
#define PC_4_PORT    GPIOC
#define PC_4_PIN     4
#define PC_4_ID      0x24
#define PC_4_ADC     14
#define PC_4_TIMER   TIMER_NONE
#define PC_4_CHANNEL 0
#define PC_4_AF      0
#define PC_4_COMPL   0
#define PC4          PC_4
#define PC_5_PORT    GPIOC
#define PC_5_PIN     5
#define PC_5_ID      0x25
#define PC_5_ADC     15
#define PC_5_TIMER   TIMER_NONE
#define PC_5_CHANNEL 0
#define PC_5_AF      0
#define PC_5_COMPL   0
#define PC5          PC_5
#define PC_6_PORT    GPIOC
#define PC_6_PIN     6
#define PC_6_ID      0x26
#define PC_6_ADC     ADC_NONE
#define PC_6_TIMER   TIM3_BASE
#define PC_6_CHANNEL 1
#define PC_6_AF      2
#define PC_6_COMPL   0
#define PC6          PC_6
#define PC_7_PORT    GPIOC
#define PC_7_PIN     7
#define PC_7_ID      0x27
#define PC_7_ADC     ADC_NONE
#define PC_7_TIMER   TIM3_BASE
#define PC_7_CHANNEL 2
#define PC_7_AF      2
#define PC_7_COMPL   0
#define PC7          PC_7
#define PC_8_PORT    GPIOC
#define PC_8_PIN     8
#define PC_8_ID      0x28
#define PC_8_ADC     ADC_NONE
#define PC_8_TIMER   TIM3_BASE
#define PC_8_CHANNEL 3
#define PC_8_AF      2
#define PC_8_COMPL   0
#define PC8          PC_8
#define PC_9_PORT    GPIOC
#define PC_9_PIN     9
#define PC_9_ID      0x29
#define PC_9_ADC     ADC_NONE
#define PC_9_TIMER   TIM3_BASE
#define PC_9_CHANNEL 4
#define PC_9_AF      2
#define PC_9_COMPL   0
#define PC9          PC_9
#define PC_10_PORT   GPIOC
#define PC_10_PIN    10
#define PC_10_ID     0x2A
#define PC_10_ADC    ADC_NONE
#define PC_10_TIMER  TIMER_NONE
#define PC_10_CHANNEL 0
#define PC_10_AF     0
#define PC_10_COMPL  0
#define PC10         PC_10
#define PC_11_PORT   GPIOC
#define PC_11_PIN    11
#define PC_11_ID     0x2B
#define PC_11_ADC    ADC_NONE
#define PC_11_TIMER  TIMER_NONE
#define PC_11_CHANNEL 0
#define PC_11_AF     0
#define PC_11_COMPL  0
#define PC11         PC_11
#define PC_12_PORT   GPIOC
#define PC_12_PIN    12
#define PC_12_ID     0x2C
#define PC_12_ADC    ADC_NONE
#define PC_12_TIMER  TIMER_NONE
#define PC_12_CHANNEL 0
#define PC_12_AF     0
#define PC_12_COMPL  0
#define PC12         PC_12
#define PC_13_PORT   GPIOC
#define PC_13_PIN    13
#define PC_13_ID     0x2D
#define PC_13_ADC    ADC_NONE
#define PC_13_TIMER  TIMER_NONE
#define PC_13_CHANNEL 0
#define PC_13_AF     0
#define PC_13_COMPL  0
#define PC13         PC_13
#define PC_14_PORT   GPIOC
#define PC_14_PIN    14
#define PC_14_ID     0x2E
#define PC_14_ADC    ADC_NONE
#define PC_14_TIMER  TIMER_NONE
#define PC_14_CHANNEL 0
#define PC_14_AF     0
#define PC_14_COMPL  0
#define PC14         PC_14
#define PC_15_PORT   GPIOC
#define PC_15_PIN    15
#define PC_15_ID     0x2F
#define PC_15_ADC    ADC_NONE
#define PC_15_TIMER  TIMER_NONE
#define PC_15_CHANNEL 0
#define PC_15_AF     0
#define PC_15_COMPL  0
#define PC15         PC_15

/* ---- Port D ---- */
#define PD_0_PORT    GPIOD
#define PD_0_PIN     0
#define PD_0_ID      0x30
#define PD_0_ADC     ADC_NONE
#define PD_0_TIMER   TIMER_NONE
#define PD_0_CHANNEL 0
#define PD_0_AF      0
#define PD_0_COMPL   0
#define PD0          PD_0
#define PD_1_PORT    GPIOD
#define PD_1_PIN     1
#define PD_1_ID      0x31
#define PD_1_ADC     ADC_NONE
#define PD_1_TIMER   TIMER_NONE
#define PD_1_CHANNEL 0
#define PD_1_AF      0
#define PD_1_COMPL   0
#define PD1          PD_1
#define PD_2_PORT    GPIOD
#define PD_2_PIN     2
#define PD_2_ID      0x32
#define PD_2_ADC     ADC_NONE
#define PD_2_TIMER   TIMER_NONE
#define PD_2_CHANNEL 0
#define PD_2_AF      0
#define PD_2_COMPL   0
#define PD2          PD_2
#define PD_3_PORT    GPIOD
#define PD_3_PIN     3
#define PD_3_ID      0x33
#define PD_3_ADC     ADC_NONE
#define PD_3_TIMER   TIMER_NONE
#define PD_3_CHANNEL 0
#define PD_3_AF      0
#define PD_3_COMPL   0
#define PD3          PD_3
#define PD_4_PORT    GPIOD
#define PD_4_PIN     4
#define PD_4_ID      0x34
#define PD_4_ADC     ADC_NONE
#define PD_4_TIMER   TIMER_NONE
#define PD_4_CHANNEL 0
#define PD_4_AF      0
#define PD_4_COMPL   0
#define PD4          PD_4
#define PD_5_PORT    GPIOD
#define PD_5_PIN     5
#define PD_5_ID      0x35
#define PD_5_ADC     ADC_NONE
#define PD_5_TIMER   TIMER_NONE
#define PD_5_CHANNEL 0
#define PD_5_AF      0
#define PD_5_COMPL   0
#define PD5          PD_5
#define PD_6_PORT    GPIOD
#define PD_6_PIN     6
#define PD_6_ID      0x36
#define PD_6_ADC     ADC_NONE
#define PD_6_TIMER   TIMER_NONE
#define PD_6_CHANNEL 0
#define PD_6_AF      0
#define PD_6_COMPL   0
#define PD6          PD_6
#define PD_7_PORT    GPIOD
#define PD_7_PIN     7
#define PD_7_ID      0x37
#define PD_7_ADC     ADC_NONE
#define PD_7_TIMER   TIMER_NONE
#define PD_7_CHANNEL 0
#define PD_7_AF      0
#define PD_7_COMPL   0
#define PD7          PD_7
#define PD_8_PORT    GPIOD
#define PD_8_PIN     8
#define PD_8_ID      0x38
#define PD_8_ADC     ADC_NONE
#define PD_8_TIMER   TIMER_NONE
#define PD_8_CHANNEL 0
#define PD_8_AF      0
#define PD_8_COMPL   0
#define PD8          PD_8
#define PD_9_PORT    GPIOD
#define PD_9_PIN     9
#define PD_9_ID      0x39
#define PD_9_ADC     ADC_NONE
#define PD_9_TIMER   TIMER_NONE
#define PD_9_CHANNEL 0
#define PD_9_AF      0
#define PD_9_COMPL   0
#define PD9          PD_9
#define PD_10_PORT   GPIOD
#define PD_10_PIN    10
#define PD_10_ID     0x3A
#define PD_10_ADC    ADC_NONE
#define PD_10_TIMER  TIMER_NONE
#define PD_10_CHANNEL 0
#define PD_10_AF     0
#define PD_10_COMPL  0
#define PD10         PD_10
#define PD_11_PORT   GPIOD
#define PD_11_PIN    11
#define PD_11_ID     0x3B
#define PD_11_ADC    ADC_NONE
#define PD_11_TIMER  TIMER_NONE
#define PD_11_CHANNEL 0
#define PD_11_AF     0
#define PD_11_COMPL  0
#define PD11         PD_11
#define PD_12_PORT   GPIOD
#define PD_12_PIN    12
#define PD_12_ID     0x3C
#define PD_12_ADC    ADC_NONE
#define PD_12_TIMER  TIM4_BASE
#define PD_12_CHANNEL 1
#define PD_12_AF     2
#define PD_12_COMPL  0
#define PD12         PD_12
#define PD_13_PORT   GPIOD
#define PD_13_PIN    13
#define PD_13_ID     0x3D
#define PD_13_ADC    ADC_NONE
#define PD_13_TIMER  TIM4_BASE
#define PD_13_CHANNEL 2
#define PD_13_AF     2
#define PD_13_COMPL  0
#define PD13         PD_13
#define PD_14_PORT   GPIOD
#define PD_14_PIN    14
#define PD_14_ID     0x3E
#define PD_14_ADC    ADC_NONE
#define PD_14_TIMER  TIM4_BASE
#define PD_14_CHANNEL 3
#define PD_14_AF     2
#define PD_14_COMPL  0
#define PD14         PD_14
#define PD_15_PORT   GPIOD
#define PD_15_PIN    15
#define PD_15_ID     0x3F
#define PD_15_ADC    ADC_NONE
#define PD_15_TIMER  TIM4_BASE
#define PD_15_CHANNEL 4
#define PD_15_AF     2
#define PD_15_COMPL  0
#define PD15         PD_15

/* ---- Port E ---- */
#define PE_0_PORT    GPIOE
#define PE_0_PIN     0
#define PE_0_ID      0x40
#define PE_0_ADC     ADC_NONE
#define PE_0_TIMER   TIMER_NONE
#define PE_0_CHANNEL 0
#define PE_0_AF      0
#define PE_0_COMPL   0
#define PE0          PE_0
#define PE_1_PORT    GPIOE
#define PE_1_PIN     1
#define PE_1_ID      0x41
#define PE_1_ADC     ADC_NONE
#define PE_1_TIMER   TIMER_NONE
#define PE_1_CHANNEL 0
#define PE_1_AF      0
#define PE_1_COMPL   0
#define PE1          PE_1
#define PE_2_PORT    GPIOE
#define PE_2_PIN     2
#define PE_2_ID      0x42
#define PE_2_ADC     ADC_NONE
#define PE_2_TIMER   TIMER_NONE
#define PE_2_CHANNEL 0
#define PE_2_AF      0
#define PE_2_COMPL   0
#define PE2          PE_2
#define PE_3_PORT    GPIOE
#define PE_3_PIN     3
#define PE_3_ID      0x43
#define PE_3_ADC     ADC_NONE
#define PE_3_TIMER   TIMER_NONE
#define PE_3_CHANNEL 0
#define PE_3_AF      0
#define PE_3_COMPL   0
#define PE3          PE_3
#define PE_4_PORT    GPIOE
#define PE_4_PIN     4
#define PE_4_ID      0x44
#define PE_4_ADC     ADC_NONE
#define PE_4_TIMER   TIMER_NONE
#define PE_4_CHANNEL 0
#define PE_4_AF      0
#define PE_4_COMPL   0
#define PE4          PE_4
#define PE_5_PORT    GPIOE
#define PE_5_PIN     5
#define PE_5_ID      0x45
#define PE_5_ADC     ADC_NONE
#define PE_5_TIMER   TIM9_BASE
#define PE_5_CHANNEL 1
#define PE_5_AF      3
#define PE_5_COMPL   0
#define PE5          PE_5
#define PE_6_PORT    GPIOE
#define PE_6_PIN     6
#define PE_6_ID      0x46
#define PE_6_ADC     ADC_NONE
#define PE_6_TIMER   TIM9_BASE
#define PE_6_CHANNEL 2
#define PE_6_AF      3
#define PE_6_COMPL   0
#define PE6          PE_6
#define PE_7_PORT    GPIOE
#define PE_7_PIN     7
#define PE_7_ID      0x47
#define PE_7_ADC     ADC_NONE
#define PE_7_TIMER   TIMER_NONE
#define PE_7_CHANNEL 0
#define PE_7_AF      0
#define PE_7_COMPL   0
#define PE7          PE_7
#define PE_8_PORT    GPIOE
#define PE_8_PIN     8
#define PE_8_ID      0x48
#define PE_8_ADC     ADC_NONE
#define PE_8_TIMER   TIM1_BASE
#define PE_8_CHANNEL 1
#define PE_8_AF      1
#define PE_8_COMPL   1
#define PE8          PE_8
#define PE_9_PORT    GPIOE
#define PE_9_PIN     9
#define PE_9_ID      0x49
#define PE_9_ADC     ADC_NONE
#define PE_9_TIMER   TIM1_BASE
#define PE_9_CHANNEL 1
#define PE_9_AF      1
#define PE_9_COMPL   0
#define PE9          PE_9
#define PE_10_PORT   GPIOE
#define PE_10_PIN    10
#define PE_10_ID     0x4A
#define PE_10_ADC    ADC_NONE
#define PE_10_TIMER  TIM1_BASE
#define PE_10_CHANNEL 2
#define PE_10_AF     1
#define PE_10_COMPL  1
#define PE10         PE_10
#define PE_11_PORT   GPIOE
#define PE_11_PIN    11
#define PE_11_ID     0x4B
#define PE_11_ADC    ADC_NONE
#define PE_11_TIMER  TIM1_BASE
#define PE_11_CHANNEL 2
#define PE_11_AF     1
#define PE_11_COMPL  0
#define PE11         PE_11
#define PE_12_PORT   GPIOE
#define PE_12_PIN    12
#define PE_12_ID     0x4C
#define PE_12_ADC    ADC_NONE
#define PE_12_TIMER  TIM1_BASE
#define PE_12_CHANNEL 3
#define PE_12_AF     1
#define PE_12_COMPL  1
#define PE12         PE_12
#define PE_13_PORT   GPIOE
#define PE_13_PIN    13
#define PE_13_ID     0x4D
#define PE_13_ADC    ADC_NONE
#define PE_13_TIMER  TIM1_BASE
#define PE_13_CHANNEL 3
#define PE_13_AF     1
#define PE_13_COMPL  0
#define PE13         PE_13
#define PE_14_PORT   GPIOE
#define PE_14_PIN    14
#define PE_14_ID     0x4E
#define PE_14_ADC    ADC_NONE
#define PE_14_TIMER  TIM1_BASE
#define PE_14_CHANNEL 4
#define PE_14_AF     1
#define PE_14_COMPL  0
#define PE14         PE_14
#define PE_15_PORT   GPIOE
#define PE_15_PIN    15
#define PE_15_ID     0x4F
#define PE_15_ADC    ADC_NONE
#define PE_15_TIMER  TIMER_NONE
#define PE_15_CHANNEL 0
#define PE_15_AF     0
#define PE_15_COMPL  0
#define PE15         PE_15

/* ---- Port H ---- */
#define PH_0_PORT    GPIOH
#define PH_0_PIN     0
#define PH_0_ID      0x70
#define PH_0_ADC     ADC_NONE
#define PH_0_TIMER   TIMER_NONE
#define PH_0_CHANNEL 0
#define PH_0_AF      0
#define PH_0_COMPL   0
#define PH0          PH_0
#define PH_1_PORT    GPIOH
#define PH_1_PIN     1
#define PH_1_ID      0x71
#define PH_1_ADC     ADC_NONE
#define PH_1_TIMER   TIMER_NONE
#define PH_1_CHANNEL 0
#define PH_1_AF      0
#define PH_1_COMPL   0
#define PH1          PH_1

/* ---- Alternative timer channels (hand-written, not generated) ----

  The table above lists one timer per pin. Some pins have a second timer
  channel on AF3 (TIM9..TIM11, APB2, 16 bit, one channel each here). These
  names are the same pin with that timer, for DEFINE_HEATER() or step pins:

    PB_8_TIM10   PB8, TIM10_CH1 (instead of TIM4_CH3)
    PB_9_TIM11   PB9, TIM11_CH1 (instead of TIM4_CH4)

  Useful when TIM1..TIM4 are all taken, e.g. by STEP_TIMER_PULSES. As plain
  GPIO they behave like PB_8 / PB_9.
*/
#define PB_8_TIM10_PORT     GPIOB
#define PB_8_TIM10_PIN      8
#define PB_8_TIM10_ID       0x18
#define PB_8_TIM10_ADC      ADC_NONE
#define PB_8_TIM10_TIMER    TIM10_BASE
#define PB_8_TIM10_CHANNEL  1
#define PB_8_TIM10_AF       3
#define PB_8_TIM10_COMPL    0
#define PB8_TIM10           PB_8_TIM10

#define PB_9_TIM11_PORT     GPIOB
#define PB_9_TIM11_PIN      9
#define PB_9_TIM11_ID       0x19
#define PB_9_TIM11_ADC      ADC_NONE
#define PB_9_TIM11_TIMER    TIM11_BASE
#define PB_9_TIM11_CHANNEL  1
#define PB_9_TIM11_AF       3
#define PB_9_TIM11_COMPL    0
#define PB9_TIM11           PB_9_TIM11

/* ---- Pins without their timer (hand-written) ----

  Same pin, no timer channel: DEFINE_HEATER() gives it software PWM even
  with a 'pwm' value above 1, e.g. when the timer drives step pulses.

    PB_0_GPIO    PB0 without TIM3_CH3 (TIM3 = E step pulses on P3 Steel)
*/
#define PB_0_GPIO_PORT      GPIOB
#define PB_0_GPIO_PIN       0
#define PB_0_GPIO_ID        0x10
#define PB_0_GPIO_ADC       8
#define PB_0_GPIO_TIMER     TIMER_NONE
#define PB_0_GPIO_CHANNEL   0
#define PB_0_GPIO_AF        0
#define PB_0_GPIO_COMPL     0
#define PB0_GPIO            PB_0_GPIO

#endif /* _PINS_STM32F4_H */
