/** \file
  \brief Babystepping (M290): move Z right away, also during a print.

  M290 Z<mm> shifts the nozzle by <mm> at once and adds the same amount to
  the Z offset, which is part of the Z correction (src/bed_leveling.c) and
  stored with M500. The logical coordinates don't change, so a print
  continues seamlessly with the new first layer height.

  The steps are generated by compare channel 3 of the step timer (TIM5),
  in the step interrupt, interleaved with the steps of running moves.
*/

#ifndef _BABYSTEP_H
#define _BABYSTEP_H

#include <stdint.h>
#include "config_wrapper.h"

#ifdef BABYSTEPPING

/// Total Z offset, um.
int32_t babystep_offset(void);

/**
  Set the Z offset without moving (settings: boot, M501, M502). The motor
  position is kept, the logical Z changes accordingly.
*/
void babystep_set_offset(int32_t um);

/**
  Move Z by 'um' now and add it to the Z offset (M290). The total is limited
  to +-BABYSTEP_LIMIT. \return the amount actually applied, um.
*/
int32_t babystep_add(int32_t um);

/// Babysteps still to do.
uint8_t babystep_busy(void);

/// Re-arm after a quickstop cleared the timer interrupts (clock_poll()).
void babystep_tick(void);

/// Compare channel 3 of TIM5, called from the step interrupt.
void babystep_isr(void);

#else

#define babystep_busy() 0
#define babystep_tick() do { } while (0)

#endif /* BABYSTEPPING */

#endif /* _BABYSTEP_H */
