# Production C translation units from both ewarm/Teacup_*.ewp projects.
SOURCES := \
  app/mendel.c \
  cmsis/system_stm32f4xx.c \
  core/babystep.c \
  core/beeper.c \
  core/buttons.c \
  core/clock.c \
  core/crc.c \
  core/debug.c \
  core/expander.c \
  core/fans.c \
  core/filament.c \
  core/flash_files.c \
  core/heater.c \
  core/home.c \
  core/host_watch.c \
  core/kill.c \
  core/mpc.c \
  core/msg.c \
  core/pid_autotune.c \
  core/power_loss.c \
  core/print_stats.c \
  core/retract.c \
  core/sd.c \
  core/sendf.c \
  core/settings.c \
  core/spindle.c \
  core/status.c \
  core/thermal_protection.c \
  core/tmc.c \
  display/display.c \
  display/display_hd44780.c \
  display/display_ssd1306.c \
  display/font_6x8.c \
  display/parallel-4bit.c \
  display/ui.c \
  hal/analog.c \
  hal/cpu.c \
  hal/delay.c \
  hal/endstops.c \
  hal/flash_store.c \
  hal/i2c.c \
  hal/pinio.c \
  hal/serial.c \
  hal/servo.c \
  hal/spi.c \
  hal/spi_flash.c \
  hal/step_timers.c \
  hal/timer.c \
  hal/tmc_uart.c \
  hal/uart.c \
  hal/usb_cdc.c \
  hal/watchdog.c \
  motion/dda.c \
  motion/dda_kinematics.c \
  motion/dda_lookahead.c \
  motion/dda_maths.c \
  motion/dda_queue.c \
  motion/input_shaping.c \
  motion/linear_advance.c \
  pff/pff.c \
  pff/pff_diskio.c \
  src/bed_leveling.c \
  src/calibration.c \
  src/emergency_parser.c \
  src/gcode_parse.c \
  src/gcode_process.c \
  src/gcode_queue.c \
  src/probe.c \
  src/temp.c \
  gcc/syscalls.c
