/** \file
  \brief Test prints generated by the firmware: mesh validation (G26),
         linear advance pattern (M9910), input shaping tower (M9911), and
         the tuning tower for slicer models (M9912).
*/

#ifndef _CALIBRATION_H
#define _CALIBRATION_H

#include <stdint.h>
#include "config_wrapper.h"

/// Test prints need the bed size.
#if defined X_MIN && defined X_MAX && defined Y_MIN && defined Y_MAX
  #define CAL_PATTERNS
#endif

/// Line geometry shared by all test prints, um.
typedef struct {
  int32_t layer;          ///< Layer height.
  int32_t width;          ///< Line width (nozzle size).
} cal_line_t;

#ifdef BED_LEVELING
/**
  G26: mesh validation pattern, like Marlin: circles at the mesh points,
  lines between them, one layer. Heats to hotend / bed (C, 0 = as it is),
  switches leveling on, primes prime_um of filament. keep: heaters stay on.
*/
void cal_g26(uint16_t hotend, uint16_t bed, const cal_line_t *line,
             int32_t prime_um, uint8_t keep);
#endif

#if defined LINEAR_ADVANCE && defined CAL_PATTERNS
/**
  M9910: linear advance pattern. One line per K from k0 to k1 in steps of
  kstep (1/10000 s): slow 20 mm, fast 40 mm, slow 20 mm. At the right K the
  line has the same width everywhere, no thin start and no blob at the end
  of the fast part.
*/
void cal_la_pattern(int32_t k0, int32_t k1, int32_t kstep, uint32_t slow,
                    uint32_t fast, const cal_line_t *line);
#endif

#if defined INPUT_SHAPING && defined CAL_PATTERNS
/**
  M9911: input shaping tower. A single wall square tower, printed fast;
  the shaper frequency (X and Y) goes linearly from f0 to f1 (1/100 Hz)
  over the height. The height with the least ringing after the corners
  gives the frequency.
*/
void cal_is_tower(uint32_t f0, uint32_t f1, int32_t height, uint32_t speed,
                  const cal_line_t *line);
#endif

/// Parameters of the tuning tower (M9912 P).
enum tower_param {
  TOWER_OFF = 0,
  TOWER_LA_K,             ///< M900 K, s.
  TOWER_IS_FREQ,          ///< M593 F, Hz, X and Y.
  TOWER_JD,               ///< M205 J, mm.
  TOWER_HOTEND,           ///< M104 S, C.
  TOWER_FLOW,             ///< M221 S, %.
  TOWER_ACCEL,            ///< M204 P, mm/s^2.
  TOWER_PARAMS
};

/**
  M9912: tuning tower for any model from the slicer (like Klipper's
  TUNING_TOWER): the parameter becomes start + factor * Z (mm), with a
  band of band_um changed only every band (value of its middle).
*/
void tower_set(uint8_t param, float start, float factor, int32_t band_um);

/// Report the tuning tower setting.
void tower_report(void);

/// G0 / G1 about to be queued with this Z (um): update the parameter.
void tower_z(int32_t z_um);

#endif /* _CALIBRATION_H */
